### ISSUE TITLE
swap EEM connectors on two-port devices

### ISSUE THREAD

**Issue by jordens** [sinara-hw/meta#1]
Due to the ribbon cable topology, the EEM connectors on a device should be right to left while keeping them on Kasli as left to right. Not doing so merely results in unnatural/unintuitive EEM slot numbers being used.

**Comment by gkasprow** [comment]
this can be done on Kasli - only silk screen modification would be needed. On existing Kasli boards one can place stickers with slot numbering.

**Comment by jordens** [comment]
I don't think that's better. Then the boards in the crate would be numbered/inserted from right to left. IMHO the Kasli numbering is correct. I'd just keep this as a "best practice" for future device designs and revisions.

**Comment by hartytp** [comment]
AFAICT, this is now done. Thanks Greg!

**Comment by hartytp** [comment]
(Would close this, but I don't have appropriate permissions for this project. @gkasprow can you either change my permissions or close this?)

**Comment by jordens** [comment]
I'll leave the permission management to @gkasprow.
