### ISSUE TITLE
EEM front panels washer cutout.

### ISSUE THREAD

**Issue by jordens** [sinara-hw/meta#3]
_From @jordens on May 15, 2018 12:46_

The cutouts that receive the rectangular snap-in grey plastic "captive" nipples for the panel mounting screws were too narrow on the older boards. The washer was squeezing the screw and not allowing it to move freely.
More recent ones seem to be fixed. Has that fix been applied to all boards?

_Copied from original issue: sinara-hw/sinara#547_

**Comment by jordens** [comment]
_From @gkasprow on May 22, 2018 21:39_

Did you observe it only with first revision or later as well?

**Comment by jordens** [comment]
The cutout was too small for all board I received until a month ago. In the last batch there were still some panels with bad cutouts but those may have been from older runs. I just wanted to make sure all panels are updated.
As a sidenote: receiving 8HP panels with 4HP handles (like for the last Kasli batch) is disappointing.

**Comment by hartytp** [comment]
@gkasprow I think this has been fixed on all boards now. Please confirm and close.

**Comment by hartytp** [comment]
@gkasprow ping...is this now fixed on all designs?

**Comment by gkasprow** [comment]
I think so.
