### ISSUE TITLE
End of Xpedition support for WUT

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/meta#32]
Mentor didn't renew the Xpedition license for WUT. Once Siemens bought Mentor, the rules changed. 
We had an agreement with mentor representative that can use non-commercial license for open-hardware activities. We still have one commercial license but it expires in March. After that, we won't have any. I got to know about it a few days ago... 
Even though Europractice offers such license, the file they sent to WUT does not contain the Xpedition. Ony PADS, Hyperlynx and a lot of others. I got to know that the Xpedition is available for qualified institutions only.
3 years ago I purchased a 3-year commercial subscription for Xpedition for 120k$ including a 70% discount. That's a lot. In a month we won't have any means to support this project.
A few months ago I purchased a 3-year AD perpetual commercial license for less than 15k$. And we have 3 such licenses in our lab. Moreover, we have 100 educational licenses but can use them for teaching only.

Yesterday I started moving design of Sayma AMC.
It takes roughly 2 days to fully translate and synchronize schematics. And one day to synchronize with PCB.
Since I used the same libraries in Xpedition and AD19, the translation is 1:1. Only the top schematic differs because buses must be replaced by harnesses.
I found a way how to translate it without risk. First I translate schematics. Then I replace all symbols with AD ones from the CERN library preserving designators. I do it in batches. 
Then the PCB is translated with all details, the translator quality in AD19 is great. No missing nets. Only 3D parts are missing.
Then I synchronize carefully PCB with SCH treating PCB as a reference. Once they are fully in sync, I replace all PCB libraries with original ones. And do sync once again resolving all the issues that arrive. In this way, all 3D parts are in place.
The final design looks designed with AD19.
This is how it looks in AD19.
![obraz](https://user-images.githubusercontent.com/4325054/52231824-341fb780-28bb-11e9-83dc-f8a644e764f0.png)

**Comment by hartytp** [comment]
FWIW ad is much better for us as we can finally open the design files here to locate components and traces.

**Comment by gkasprow** [comment]
True, AD has a very good free viewer.

**Comment by sbourdeauducq** [comment]
> Moreover, we have 100 educational licenses but can use them for teaching only.

Please make sure that this story is part of what the students learn about Mentor and similar tools.
