### ISSUE TITLE
MCX adapter for Sampler, BNC-DIO, IDC-BNC

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/meta#33]
Technosystem volunteered to design a simple adapter that can be mounted instead of BNC connectors and utilize existing boards with 4HP panels. In this way, all modules already available with BNC connectors can be easily modified with MCX or other connectivity option.
Moreover, existing modules can be easily transformed by the users to 4HP by ordering kits containing adapter and 4 HP panel. In this way, it will be much easier to manage the stock of boards and offer various configuration options.
What do you think? @jordens @hartytp

**Comment by hartytp** [comment]
Personally I'm not overly fussed about the BNC/MCX issue. I wouldn't expect us to bother modifying any of our BNC boards to use MCXs, and I'd be happy to keep buying BCN versions until stocks are exhausted.

**Comment by jordens** [comment]
Same here. Bnc is fine until exhausted.
Do I get that right that this would be a reverse mezzanine with mcx (and chokes ?) and the bncs on sampler would not be populated?

**Comment by gkasprow** [comment]
This will be tiny mezzanine soldered to the BNC pads,  with MCX connectors on it. This would fit Sampler, DIO, IDC-BNC. In this way, the modules could be ordered with MCX or BNC or converted later on.

**Comment by gkasprow** [comment]
Here is the design
![obraz](https://user-images.githubusercontent.com/4325054/59967158-a02b5100-9526-11e9-8b74-437248187384.png)
Sampler with MCX option

![obraz](https://user-images.githubusercontent.com/4325054/59967175-de287500-9526-11e9-9312-4f0176961ac5.png)
![obraz](https://user-images.githubusercontent.com/4325054/59967178-ea143700-9526-11e9-87a4-b1c42a2f7ece.png)

DIO with MCX
![obraz](https://user-images.githubusercontent.com/4325054/59967204-568f3600-9527-11e9-9464-434ea166da0d.png)

**Comment by gkasprow** [comment]
and IDC version
![obraz](https://user-images.githubusercontent.com/4325054/59967285-2dbb7080-9528-11e9-8325-0937b9609c54.png)

**Comment by dtcallcock** [comment]
It looks great.  What makes the connection between the main PCB and the adaptor though? 

How is isolation from the front panel achieved?  Just a gap around the MCX?

**Comment by gkasprow** [comment]
> It looks great. What makes the connection between the main PCB and the adaptor though?
> 

pieces of wire soldered on both sides

> How is isolation from the front panel achieved? Just a gap around the MCX?

yes

**Comment by gkasprow** [comment]
The boards are connected using 11 mm standoffs. The MCX would probably need the shrink tube rings around.

**Comment by hartytp** [comment]
Cool. Is the plan to release a version of sampler etc with he mcx on directly soon, or do you want to keep using these adapters for a while?

**Comment by gkasprow** [comment]
I want to keep for a while. Clients still want BNC version.

**Comment by gkasprow** [comment]
Such solution won't have an influence on the cost.

**Comment by gkasprow** [comment]
I've sent it for fabrication.

**Comment by jordens** [comment]
@gkasprow could you spin a repository for this and publish design files + release PDFs? Did the prototype work?

**Comment by gkasprow** [comment]
Yes, it worked. I don't have photos with me but did not see any issues.
