### ISSUE TITLE
SiPM detectors

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/meta#35]
I'm building recently an acquisition system for roughly 4k SiPM (Silicon PhotoMultiplier) channels.
The front-end will be equipped with 70V bias LDO, temperature sensor, tiny CPU that takes care about temperature compensation of the SiPM bias voltage, dual SiPM detectors spaced by 80mm and OTA with diff drivers.  CPUs are controlled over CAN
The signals will be transferred using USB-C cables (they have 4 twinax pairs capable of 5GHz at least) to the hub that collects the signals and then transfers them using 10-meter mSAS cables to FMC boards with 100MS/s ADC and TDCs. They are installed on AFCK boards in the MTCA crate.
The hub and AFE boards are supplied over PoE (16 channels). On each hub there is Ethernet - CAN converter based on STM32. I will probably use microPython to make physicists life easier.
We will measure both the ToF and energy of the photons. All AFE channels receive common LVPECL calibration pulse to calibrate cable delays.
We're gaining a lot of experience with these SiPM detectors and I'm curious if parts of the design could be useful for the quantum community.
I'm using Hamamatsu SiPD. The idea is to use Migen to write all gateware for AFCK and in this way introduce it to the HEP community. 
The design is open-source.[ FMC-ADC-TDC](https://github.com/gkasprow/FMC_ADC100M_10B_TDC_16cha) schematics are already on my github.

**Comment by jordens** [comment]
AFAIK SiPMs are not used in matter ion trapping or neutrals. Maybe the ALPHA/BASE people would be a closer target. Energy resolution is generally not that sought after for cold matter and well known photon energies.
But maybe the SNSPD stuff (superconducting nanowire) would be interesting for this once there are many on a chip. And they bias with (small) current, not voltage.
