### ISSUE TITLE
summer releases

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/meta#42]
@gkasprow several of the sinara designs have small issues (some of which have been open for quite a while). Do you think we can do a bit of bug fixing, with the aim of a new set of releases in the next couple of months?

**Comment by gkasprow** [comment]
Yes, I plan to release new versions of most of the boards once I come back from the US.
What is the priority list?
I assume:
- Urukul
- Thermostat
- Stabilizer

**Comment by hartytp** [comment]
Sounds like the right priority order.

IIRC there are a few other boards needing fixes as well. Probably best to just check through all the designs in sinara-hw and see what needs doing...

**Comment by jbqubit** [comment]
Agreed that Urukul is the highest priority.

**Comment by hartytp** [comment]
Would also be good to get a new stabilizer release soon.

**Comment by hartytp** [comment]
@gkasprow are any boards ready for review yet?
