### ISSUE TITLE
PG resistor

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/meta#43]
TPS74901RGWT specify an absolute maximum PG current as 1.5mA. It's currently pulled up to 7V5 by 1k2 so can easily exceed this. In practice this is probably okay since it's only a brief transient condition. Still, we may as well increase the PG resistor value to avoid exceeding the part's abs max rating.

**Comment by gkasprow** [comment]
wrong issue #

**Comment by gkasprow** [comment]
I already fixed that.
