### ISSUE TITLE
Technosystem purchasing page link is broken

### ISSUE THREAD

**Issue by dnadlinger** [sinara-hw/meta#45]
The TechnoSystem Sinara hardware sales page link at https://github.com/sinara-hw/meta/wiki/Purchasing currently leads to an empty page with invalid SSL certificate. (I've never tried to use it before, so no idea if it ever worked.)

**Comment by drewrisinger** [comment]
I think it has been broken as of a few months ago, last time I tried it.

**Comment by dnadlinger** [comment]
I've removed the broken link for now, as it seemed to suggest that the TechnoSystem hardware effort is in a much worse state than it actually is. An overview page would definitely be interesting for some users, though.

**Comment by hartytp** [comment]
The TS link used to work. Last time I spoke to them (a week or so ago) they were in the process of making a new Sinara shopping page, which is expected to come live soon. For now, just email Pawel.

**Comment by sbourdeauducq** [comment]
Soon (ETA sometime in November) there will be a nice system for ordering fully assembled crates from M-Labs and QUARTIQ.
[case -02-desktop.pdf](https://github.com/sinara-hw/meta/files/3639232/case.-02-desktop.pdf)
[case -02-mobile.pdf](https://github.com/sinara-hw/meta/files/3639233/case.-02-mobile.pdf)

**Comment by dtcallcock** [comment]
Looks slick!

Would be good to have version numbers on the boards.

**Comment by dhslichter** [comment]
I love it!  Definitely want to have board version numbers.  This will be nice.  Will there also be ordering of single boards, or will this still go through Technosystem or Creotech?

**Comment by dhslichter** [comment]
@marmeladapk any update on a technosystem ordering page?

**Comment by hartytp** [comment]
TS are still working on their new ordering page. For you you need to email them
