### ISSUE TITLE
QC issues

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/meta#8]
We had a few soldering / qc issues with the previous batch of EEMs. e.g. https://github.com/sinara-hw/Zotino/issues/3#issuecomment-413104662

@gkasprow what's the plan for resolving them going forwards? Please close this issue once you're satisfied that these issues will be resolved in future production rounds.

**Comment by gkasprow** [comment]
Technosystem claim they had series of connectors with poor lead wetting. But this still should be detected by the QC anyway. AOI is performed only on SMT assembly. We have to force them to do inspection on THT as well.

**Comment by jordens** [comment]
Another one. Who can spot the stray resistor? It's semi-soldered. Shouldn't AOI see that?
This is DIO_BNC/v1.2, TS 36/18
![img_20180822_092954](https://user-images.githubusercontent.com/1338946/44449445-76478c00-a5ee-11e8-88a5-c001cf08af86.jpg)

**Comment by hartytp** [comment]
@gkasprow closing this as there doesn't seem to be any outstanding action here. We should continue to discuss these QC issues with TechnoSystem if we're going to keep using them as a supplier.

**Comment by gkasprow** [comment]
In case of QC issues, notify the vendor directly. They are usually not following these threads.
