### ISSUE TITLE
Default Sinara font

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/meta#86]
We have issues with the Altium font that is used in all front panels
Altium does not produce correct outputs when the font is set to "stroke"; we have to use Altium 19 to generate outputs which may lead to issues because it's error-prone.
![image](https://github.com/sinara-hw/meta/assets/4325054/78254b57-7c98-4658-9f48-b89c1ebeaec3)

Guys from CTI are using "Segoe semibold"; Altium has Segoe UI Semibold
![image](https://github.com/sinara-hw/meta/assets/4325054/68d8b730-4596-409f-a12f-5c45de255a3d)

While guys from TS are using Ubuntu Mono, but it is not available in Altium
![image](https://github.com/sinara-hw/meta/assets/4325054/57e9e7ce-bba9-4ff1-87fc-58eddabbca9a)

I want to make sure all panels from different vendors look the same.
So, unless there are objections, I'd like to switch to Segoe UI Semibold

**Comment by jordens** [comment]
No objections from me. Checked license and availability. Doesn't need to be fixed-width.
Thanks for the effort!

**Comment by jmoskwa** [comment]
Slight correction - in CTI it is exactly "Segoe UI Semibold", so the same as in Altium.

**Comment by maciejprzybysz** [comment]
As Altium Stroke is a problem for a long time we introduced Ubuntu Mono as fully open source font in our panels/projects for some time. This was preceded by researching the possibilities and choosing a font that could be used everywhere, not only in Altium.

Windows fonts could be used commercially only if you have Microsoft commercial license. This means that e.g. Home & Student versions of Windows/Office do not allow the use of this font commercially. You also cannot use this font commercially by uploading it to Linux machine, web hosting without a Microsoft commercial license, etc. Ubuntu Mono is fully open source, has no restrictions in commercial uses.

https://learn.microsoft.com/pl-pl/typography/fonts/font-faq

Monospace font looks better when you place multiple overlays nearby or when you need to maintain fixed spacing. This is also how Altium Stroke behaves, so we wanted to keep this feature.

Ubuntu mono is visually very similar to Altium Stroke. It could be imported to Windows/Linux System Fonts and used in any program that you want (Altium / Inventor / Solid).

We also made a lot of work with panel projects. 3D models in our revisions has also Panels with overlay made with Ubuntu mono.

![2024-02-01_14h33_33](https://github.com/sinara-hw/meta/assets/48446953/f2acbea7-d831-462b-8a7f-c88c0b522aea)

So please take this into consideration.

@gkasprow @jordens

**Comment by jordens** [comment]
While I agree that a fully open font would be better, I don't think the "redistribution FAQ" (!) and associated limitations apply here. It's not about redistributing the font. If you possess a legitimately obtained copy of the font (e.g. through Altium), you may use it!

**Comment by gkasprow** [comment]
How to install fonts in Altium? Is it enough to import to WIndows font directory?
 The other issue is when sb opens project in Altium, the missing font will be substituted by Arial

**Comment by maciejprzybysz** [comment]
@gkasprow 

Altium uses System fonts, so all fonts that are installed in Windows are available in Altium.

https://support.microsoft.com/en-us/office/add-a-font-b7c5f17c-4426-4b53-967f-455339c564c1

@jordens 

The issue with font redistribution could be taken into consideration in situations like printing advertising materials by TS or CTI or using this font on our websites.

**Comment by maciejprzybysz** [comment]
> The other issue is when sb opens project in Altium, the missing font will be substituted by Arial

Installing font is not necessary for viewing project. It is only necessary for editing.

![image](https://github.com/sinara-hw/meta/assets/48446953/d8d559c0-82b4-45af-8981-ed3cf6998459)

(Second font is Arial, but description is wrong, sorry for that)

You could check this by downloading sample PCB file: 
[PCB1.zip](https://github.com/sinara-hw/meta/files/14126530/PCB1.zip)

**Comment by jordens** [comment]
> The issue with font redistribution could be taken into consideration in situations like printing advertising materials by TS or CTI or using this font on our websites.

But this is about the panels and not about your website, right? And I believe even if you put up artwork created using some font on your website, you wouldn't be redistributing said font, right?

**Comment by maciejprzybysz** [comment]
For now this is not an issue, but we have some ideas for the future and we would like to have one universal font for Sinara that have no restrictions in license for any kind of use. Including printing and publishing on website. Of course we could handle this anyway, but why not to choose a more versatile solution?

**Comment by jmoskwa** [comment]
I believe we need to focus on panels first as they are in production already.

**Comment by gkasprow** [comment]
I think Ubuntu mono looks very similar to stroke font and it's hard to distinguish such panels. Since TS did a lot of work on high-quality documentation for several modules, let's stick with this font for all new module revisions.
This applies to panels on sinara modules. When we build stand-alone devices, this is optional.

**Comment by jordens** [comment]
Sounds good to me. I wouldn't take a mono font as I don't see any advantage (it's a clear disadvantage in readability). But if it simplifies things and is compatible with at least a significant existing panels, that's fine.
Are there plans to push those new panel designs to the repos as well? I for one would very much apreciate it.

**Comment by gkasprow** [comment]
Some of them are already in the repo, am I right @maciejprzybysz ?

**Comment by maciejprzybysz** [comment]
They are pushed only as embedded step 3D model in Altium projects. We didn't made Altium Panel PCB as we use MCAD to design panels. It is more suitable for this.

**Comment by gkasprow** [comment]
Can you share some 2D files for modified panels?
Just text in dwg or sth similar.

**Comment by gkasprow** [comment]
I copied the fonts to C:\Windows\Fonts and it works under Altium.
I thin we can close the issue.
